server:
  port: 5757
spring:
  application:
    name: eureka-service
ribbon:
  eureka:
    enabled: false
eureka:
  instance:
    hostname: 91.186.197.234
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  server:
    waitTimeInMsWhenSyncEmpty: 15000

